In [24]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [25]:
df = pd.read_csv("../result.csv", sep=";", header=None)
df.sort_values(by=df.columns[0], ascending = False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
16951,209.79,2202.8,10.50,moonfire,moonfire,starfall,starfall,starfall,moonfire,wrath,starfall,starfall,moonfire,moonfire,wrath,starfall,wrath,wrath,starfall,starfall,wrath,starfall,wrath,starfall,moonfire,wrath,wrath,moonfire,wrath,moonfire,wrath,wrath,starfall
22471,193.27,2222.6,11.50,wrath,wrath,moonfire,moonfire,starfall,starfall,starfall,starfall,wrath,starfall,starfall,moonfire,starfall,starfall,starfall,wrath,starfall,wrath,wrath,starfall,starfall,wrath,starfall,moonfire,wrath,wrath,wrath,wrath,starfall,starfall
38715,190.58,2096.4,11.00,wrath,moonfire,moonfire,wrath,moonfire,moonfire,starfall,wrath,moonfire,wrath,moonfire,starfall,starfall,wrath,wrath,starfall,starfall,wrath,wrath,starfall,wrath,wrath,wrath,starfall,wrath,wrath,wrath,wrath,wrath,starfall
63377,181.05,1901.0,10.50,wrath,moonfire,wrath,moonfire,wrath,moonfire,wrath,moonfire,moonfire,moonfire,wrath,moonfire,starfall,starfall,wrath,starfall,starfall,wrath,wrath,starfall,wrath,wrath,moonfire,starfall,wrath,wrath,starfall,wrath,starfall,wrath
81110,156.43,2033.6,13.00,moonfire,wrath,wrath,wrath,moonfire,starfall,wrath,wrath,moonfire,moonfire,starfall,wrath,wrath,starfall,starfall,wrath,wrath,starfall,starfall,wrath,moonfire,starfall,wrath,moonfire,wrath,moonfire,starfall,moonfire,wrath,wrath
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91022,23.98,1515.8,63.20,moonfire,moonfire,moonfire,starfall,moonfire,starfall,moonfire,moonfire,wrath,wrath,moonfire,wrath,moonfire,moonfire,wrath,wrath,wrath,wrath,moonfire,moonfire,moonfire,moonfire,moonfire,wrath,moonfire,moonfire,starfall,moonfire,moonfire,moonfire
99426,23.84,1414.8,59.34,moonfire,starfall,moonfire,moonfire,wrath,moonfire,wrath,moonfire,wrath,starfall,moonfire,moonfire,moonfire,moonfire,wrath,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,wrath,starfall,moonfire,starfall,moonfire,moonfire
36470,23.57,1524.8,64.70,starfall,moonfire,wrath,moonfire,starfall,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,wrath,moonfire,wrath,moonfire,moonfire,starfall,wrath,wrath,moonfire,starfall,moonfire,moonfire,moonfire,starfall,starfall,moonfire,moonfire
74292,23.06,1476.6,64.04,moonfire,moonfire,moonfire,starfall,wrath,moonfire,starfall,moonfire,moonfire,moonfire,wrath,moonfire,wrath,moonfire,moonfire,starfall,wrath,moonfire,moonfire,starfall,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,starfall,moonfire,moonfire,moonfire
51873,21.47,1335.2,62.20,starfall,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,moonfire,wrath,moonfire,wrath,wrath,moonfire,wrath,moonfire,wrath,moonfire,moonfire,moonfire,wrath,moonfire,moonfire,moonfire,moonfire,moonfire,wrath,moonfire

In [13]:
df.head(100)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,23.37,701.0,30.00,starfall,moonfire,moonfire,starfall,wrath,moonfire,starfall,starfall,starfall,moonfire
1,23.95,718.4,30.00,starfall,starfall,moonfire,starfall,starfall,wrath,moonfire,moonfire,starfall,moonfire
2,25.85,850.0,32.88,wrath,starfall,wrath,starfall,starfall,wrath,wrath,wrath,moonfire,moonfire
3,27.91,725.6,26.00,starfall,moonfire,wrath,moonfire,moonfire,wrath,moonfire,starfall,wrath,wrath
4,25.32,785.8,31.04,wrath,starfall,wrath,wrath,wrath,moonfire,starfall,wrath,moonfire,starfall
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,29.23,716.2,24.50,moonfire,moonfire,wrath,starfall,wrath,wrath,starfall,wrath,wrath,starfall
96,20.37,556.8,27.34,wrath,wrath,moonfire,moonfire,wrath,moonfire,wrath,starfall,starfall,wrath
97,20.42,678.0,33.20,starfall,moonfire,moonfire,starfall,moonfire,starfall,moonfire,moonfire,wrath,moonfire
98,37.77,837.8,22.18,wrath,wrath,starfall,wrath,starfall,moonfire,wrath,starfall,wrath,wrath
99,31.45,866.2,27.54,wrath,wrath,moonfire,wrath,starfall,wrath,moonfire,wrath,starfall,starfall